experiment:
  data_config:
    strategy: dataset
    dataset_path: ../data/{0}/trainingset.tsv
  splitting:
    save_on_disk: True
    save_folder: ../data/{0}/splitting/
    test_splitting:
        strategy: random_subsampling
        leave_n_out: 1
        folds: 1
#    validation_splitting:
#        strategy: fixed_timestamp|temporal_hold_out|random_subsampling|random_cross_validation
#        timestamp: best|1609786061
#        test_ratio: 0.2
#        leave_n_out: 1
#        folds: 5
  prefiltering:
    strategy: global_threshold
    relevance_threshold: 0
    core: 5
    rounds: 2
  dataset: example
  path_output_rec_result: ../results/{0}/recs/
  path_output_rec_weight: ../results/{0}/weights/
  path_output_rec_performance: ../results/{0}/performance/
  path_logger_config: ./config/logger_config.yml
  path_log_folder: ../log/
  top_k: 50
  evaluation:
    cutoff: 10
    simple_metrics: [ nDCG, Precision, Recall, ItemCoverage, HR, MRR, MAP, F1, Gini, SEntropy, EFD, EPC, LAUC]
    relevance: 1
    paired_ttest: True
    complex_metrics:
    - metric: UserMADrating
      clustering_name: Happiness
      clustering_file: /home/cheggynho/Documents/UMUAI2019FatRec/ml-1m-2020-03-08/Clusterings/UsersClusterings/user_clustering_happiness.tsv
    - metric: DSC
      beta: 2
  gpu: -1 # -1 is not use GPU
  models:
    Random:
      meta:
        save_recs: True
    MultiDAE:
      meta:
        hyper_max_evals: 1
        hyper_opt_alg: tpe
        validation_rate: 10
        verbose: False
        save_weights: False
        save_recs: True
      lr: 0.001
      epochs: 50
      intermediate_dim: 600
      latent_dim: 200
      batch_size: -1
      dropout_pkeep: 1
      reg_lambda: 0.01