experiment:
  dataset: movielens_1m
  data_config:
    strategy: dataset
    dataset_path: ../data/movielens_1m/dataset.tsv
  splitting:
    test_splitting:
        strategy: random_subsampling
        test_ratio: 0.2
  top_k: 10
  evaluation:
    simple_metrics: [HR]
  gpu: -1
  models:
    AMF:
      meta:
        save_recs: True
        hyper_max_evals: 5
        hyper_opt_alg: tpe
      epochs: 20
      batch_size: 256
      factors: [50, 100]
      lr: [0.001, 0.1]
      l_w: 0.0001
      l_b: 0.0001
      eps: [0.1, 0.5] # Magnitude of the Perturbation
      l_adv: 1 # Adversarial Regularization Parameters
      adversarial_epochs: [5, 15] # Number of final epochs to be run [APR starts from (epochs - adversarial_epochs) epoch]