experiment:
  data_config:
    strategy: fixed
    dataloader: KnowledgeChainsLoader
    train_path: ../data/{0}/trainingset.tsv
    test_path: ../data/{0}/testset.tsv
    side_information:
        map: ../data/{0}/map.tsv
        features: ../data/{0}/features.tsv
        properties: ../data/{0}/properties.conf
  dataset: categorical_dbpedia_ml1m
  path_output_rec_result: ../results/{0}/recs/
  path_output_rec_weight: ../results/{0}/weights/
  path_output_rec_performance: ../results/{0}/performance/
  path_logger_config: ./config/logger_config.yml
  path_log_folder: ../log/
  top_k: 50
  evaluation:
    cutoff: [5,10]
    simple_metrics: [nDCG, Precision, Recall, ItemCoverage, HR, MAP, F1, Gini, SEntropy, EFD, EPC]
    relevance_threshold: 3
    paired_ttest: True
#    complex_metrics:
#    - metric: UserMADrating
#      clustering_name: Happiness
#      clustering_file: ../data/categorical_dbpedia_ml1m/user_clustering_happiness.tsv
#    - metric: DSC
#      beta: 2
#    - metric: SRecall
#      feature_data: ../data/categorical_dbpedia_ml1m/map.tsv
  gpu: 1 # -1 is not use GPU
  models:
    MultiVAE:
      meta:
        hyper_max_evals: 2
        hyper_opt_alg: tpe
        validation_rate: 10
        verbose: False
        save_weights: False
        save_recs: False
      lr: 0.01
      epochs: [10,20]
      intermediate_dim: 300
      latent_dim: 100
      batch_size: -1
      dropout_pkeep: 1
      reg_lambda: 0.01
    KaHFMBatch:
      meta:
        hyper_max_evals: 20
        hyper_opt_alg: tpe
        validation_rate: 10
        verbose: True
        save_weights: False
        save_recs: True
        validation_metric: nDCG
        restore_epoch: -1
      lr: 0.0001
      epochs: 10
      batch_size: 512
      l_w: 0.005
      l_b: 0
    MultiDAE:
      meta:
        hyper_max_evals: 1
        hyper_opt_alg: tpe
        validation_rate: 1
        verbose: True
        save_weights: False
        save_recs: False
      lr: 0.001
      epochs: 1
      intermediate_dim: 600
      latent_dim: 200
      batch_size: -1
      dropout_pkeep: 1
      reg_lambda: 0.01
    BPRMF:
      meta:
        hyper_max_evals: 1
        hyper_opt_alg: tpe
        validation_rate: 1
        verbose: True
        save_weights: False
        save_recs: False
        validation_metric: nDCG
        restore_epoch: -1
      lr: 0.05
      epochs: 1
      embed_k: 10
      bias_regularization: 0
      user_regularization: 0.005
      positive_item_regularization: 0.0025
      negative_item_regularization: 0.00025
      update_negative_item_factors: True
      update_users: True
      update_items: True
      update_bias: True
    NNBPRMF:
      meta:
        hyper_max_evals: 1
        hyper_opt_alg: tpe
        validation_rate: 1
        verbose: True
        save_weights: False
        save_recs: False
        validation_metric: nDCG
        restore_epoch: -1
      lr: 0.001
      epochs: 1
      embed_k: 50
      batch_size: 512
      l_w: 0.0025
      l_b: 0
    KaHFM:
      meta:
        hyper_max_evals: 1
        hyper_opt_alg: tpe
        validation_rate: 1
        verbose: True
        save_weights: False
        save_recs: True
        validation_metric: nDCG
        restore_epoch: -1
      lr: 0.05
      epochs: 1
      bias_regularization: 0
      user_regularization: 0.0025
      positive_item_regularization: 0.0025
      negative_item_regularization: 0.00025
      update_negative_item_factors: True
      update_users: True
      update_items: True
      update_bias: True
      Random:
        meta:
          save_recs: False
    ItemKNN:
      meta:
        verbose: True
        save_recs: False
      neighbors: 50
      similarity: cosine
      implementation: aiolli