experiment:
  data_config:
    strategy: fixed
    train_path: ../data/{0}/trainingset.tsv
    test_path: ../data/{0}/testset.tsv
  dataset: categorical_dbpedia_ml1m
  path_output_rec_result: ../results/{0}/recs/
  path_output_rec_weight: ../results/{0}/weights/
  path_output_rec_performance: ../results/{0}/performance/
  path_logger_config: ./config/logger_config.yml
  path_log_folder: ../log/
  top_k: 50
  evaluation:
    cutoff: 10
    simple_metrics: [ nDCG, Precision, Recall, ItemCoverage, HR, MRR, MAP, F1, Gini, SEntropy, EFD, EPC, LAUC]
    relevance_threshold: 1
    paired_ttest: True
  gpu: -1 # -1 is not use GPU
  models:
    ItemKNN:
      meta:
        verbose: False
#        save_weights: True
        save_recs: True
#      restore: True
      neighbors: 50
      similarity: cosine
      implementation: aiolli
#    Random:
#      meta:
#        save_recs: True
#    MultiDAE:
#      meta:
#        hyper_max_evals: 1
#        hyper_opt_alg: tpe|atpe|mix|rand|anneal
#        validation_rate: 10
#        verbose: False
#        save_weights: False
#        save_recs: True
#      lr: 0.001
#      epochs: 50
#      intermediate_dim: 600
#      latent_dim: 200
#      batch_size: -1
#      dropout_pkeep: 1
#      reg_lambda: 0.01
#    MultiVAE:
#      meta:
#        hyper_max_evals: 2
#        hyper_opt_alg: tpe
#        validation_rate: 10
#        verbose: False
#        save_weights: False
#        save_recs: True
#      lr: 0.01
#      epochs: [50,20]
#      intermediate_dim: 300
#      latent_dim: 100
#      batch_size: -1
#      dropout_pkeep: 1
#      reg_lambda: 0.01