experiment:
  dataset: movielens_1m
  data_config:
    strategy: dataset
    dataset_path: ../data/movielens_1m/dataset.tsv
  splitting:
    test_splitting:
        strategy: random_subsampling
        test_ratio: 0.2
  top_k: 10
  evaluation:
    cutoffs: 10
    simple_metrics: [nDCG, recall]
#  gpu: -1
  external_models_path: ../external/models/__init__.py
  models:
#    external.MostPop:
#      meta:
#        verbose: True
#        save_recs: False
    external.EASER:
      meta:
        verbose: True
        save_recs: False
      l2_norm: 3e3
#    external.RP3beta:
#      meta:
#        verbose: True
#        save_recs: False
#      neighborhood: 100
#      alpha: 1
#      beta: 0.6
#      min_rating: 3
#      implicit: False
#      normalize_similarity: True