experiment:
  dataset: movielens_1m
  data_config:
    strategy: dataset
    dataset_path: ../data/movielens_1m/dataset.tsv
  prefiltering:
    - strategy: global_threshold
      threshold: 4
    - strategy: iterative_k_core
      core: 10
  binarize: True
  splitting:
    test_splitting:
        strategy: random_subsampling
        test_ratio: 0.2
  negative_sampling:
    strategy: random
    num_items: 99
  top_k: 10
  evaluation:
    cutoffs: 10
    simple_metrics: [nDCG, recall]
#  gpu: -1
  external_models_path: ../external/models/__init__.py
  models:
#    Random:
#      meta:
#        save_recs: False
#    external.MostPop:
#      meta:
#        verbose: True
#        save_recs: False
#        save_weights: False
#    MultiVAE:
#      meta:
##        hyper_max_evals: 3
##        hyper_opt_alg: tpe
##        validation_rate: 10
#        verbose: True
##        save_weights: True
#        save_recs: False
#        restore: False
#        optimize_internal_loss: True
#      lr: 0.002718457840118028
#      epochs: 10
#      intermediate_dim: 91
#      latent_dim: 100
#      batch_size: -1
#      dropout_pkeep: 1
#      reg_lambda: 0.01
#    external.RendleMF:
#      meta:
#        verbose: True
#        save_recs: False
#      epochs: 10
#      factors: 10
#      lr: 0.01
#      reg: 0.0025
#    external.EASER:
#      meta:
#        verbose: True
#        save_recs: False
#      l2_norm: 3e3
    external.RP3beta:
      meta:
        verbose: True
        save_recs: False
      neighborhood: 100
      alpha: 1
      beta: 0.6
      normalize_similarity: True