experiment:
  dataset: movielens_1m
  data_config:
    strategy: dataset
    dataset_path: ../data/movielens_1m/dataset.tsv
  splitting:
    test_splitting:
        strategy: random_subsampling
        test_ratio: 0.2
  negative_sampling:
    strategy: random
    num_items: 99
  top_k: 10
  evaluation:
    cutoffs: 10
    simple_metrics: [nDCG, recall]
#  gpu: -1
  external_models_path: ../external/models/__init__.py
  models:
    MultiVAE:
      meta:
#        hyper_max_evals: 3
#        hyper_opt_alg: tpe
#        validation_rate: 10
        verbose: True
#        save_weights: True
        save_recs: False
        restore: False
        optimize_internal_loss: True
      lr: 0.002718457840118028
      epochs: 10
      intermediate_dim: 91
      latent_dim: 100
      batch_size: -1
      dropout_pkeep: 1
      reg_lambda: 0.01
#    external.MostPop:
#      meta:
#        verbose: True
#        save_recs: True
#        save_weights: True
#    external.EASER:
#      meta:
#        verbose: True
#        save_recs: False
#      l2_norm: 3e3
#    external.RP3beta:
#      meta:
#        verbose: True
#        save_recs: False
#      neighborhood: 100
#      alpha: 1
#      beta: 0.6
#      min_rating: 3
#      implicit: False
#      normalize_similarity: True