experiment:
  path_train_data: ../data/{0}/trainingset.tsv
  path_validation_data: ../data/{0}/validation.tsv
  path_test_data: ../data/{0}/testset.tsv
  path_feature_data: ../data/{0}/features.tsv
  path_output_rec_result: ../results/{0}/recs/
  path_output_rec_weight: ../results/{0}/weights/
  path_output_rec_performance: ../results/{0}/performance/
  dataset: example
  top_k: 50
  metrics: [nDCG,Precision, Recall, ItemCoverage]
  relevance: 1
  gpu: -1 # -1 is not use GPU
  models:
    BPRMF:
      lr: [0.01, 0.05]
      epochs: 2
      embed_k: [20, 40]
      batch_size: 512
      bias_regularization: 1
      user_regularization: 1
      positive_item_regularization: 1
      negative_item_regularization: 1
      update_negative_item_factors: True
      update_users: True
      update_items: True
      update_bias: True
      hyper_max_evals: 2
      hyper_opt_alg: tpe
    NNBPRMF:
      lr: 0.01
      epochs: 2
      embed_k: 20
      batch_size: 512
      l_w: 1
      l_b: 1