experiment:
  training_set: ../data/{0}/trainingset.tsv
  validation_set: ../data/{0}/validation.tsv
  test_set: ../data/{0}/testset.tsv
  features: ../data/{0}/features.tsv
  recs: ../results/{0}/recs/
  weights: ../results/{0}/weights/
  performance: ../results/{0}/performance/
  dataset: example
  top_k: 50
  metrics: [Precision, Recall, ItemCoverage]
  relevance: 1
  models:
    BPRMF:
      lr: [0.01, 0.05]
      epochs: 2
      embed_k: [20, 40]
      batch_size: 512
      bias_regularization: 1
      user_regularization: 1
      positive_item_regularization: 1
      negative_item_regularization: 1
      update_negative_item_factors: True
      update_users: True
      update_items: True
      update_bias: True
      hyper_max_evals: 2