version: 1
objects:
  queue:
    class: queue.Queue
    maxsize: 10000
formatters:
  simple:
    format: '%(asctime)-15s %(levelname)s %(message)s'
    datefmt: '%a %d %b %Y %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: FATAL
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: FATAL
    filename: !CUSTOM ${log_path_exp}
    formatter: simple
  queue_listener:
    class: elliot.utils.logger_util.QueueListenerHandler
    handlers:
      - cfg://handlers.console
      - cfg://handlers.file
    queue: cfg://objects.queue
loggers:
  'recommender':
    level: FATAL
    handlers:
      - queue_listener
    propagate: false
  'DataSet':
    level: FATAL
    handlers:
      - queue_listener
  'KnowledgeChainsLoader':
    level: FATAL
    handlers:
      - queue_listener
  'KnowledgeChainsDataObject':
    level: FATAL
    handlers:
      - queue_listener
  'DataSetLoader':
    level: FATAL
    handlers:
      - queue_listener
  'Evaluator':
    level: FATAL
    handlers:
      - queue_listener
  'namespace':
    level: FATAL
    handlers:
      - queue_listener
  'hyperparam':
    level: FATAL
    handlers:
      - queue_listener
  'prefiltering':
    level: FATAL
    handlers:
      - queue_listener
  'splitter':
    level: FATAL
    handlers:
      - queue_listener
  'result_handler':
    level: FATAL
    handlers:
      - queue_listener
  __main__:
    level: FATAL
    handlers:
      - queue_listener
    propagate: false
root:
  level: FATAL
  handlers:
    - console